### ISSUE TITLE
6. Creating the Gif Object

### ISSUE THREAD

**Issue by ellojess** [MakeSchool-Tutorials/Giphy-Search-iOS#1]
/**
    Fetches gifs based on the search term and populates tableview
    - Parameter searchTerm: The string to search gifs of
    */
    func fetchGifs(for searchText: String) {
        network.fetchGiphs(searchTerm: searchText) { results in
            if results != nil {
                print(results!.giphs.count)
                self.giphs = results!.giphs
                self.tableView.reloadData()
            }
        }
    }

should be: 

        /**
        Fetches gifs based on the search term and populates tableview
        - Parameter searchTerm: The string to search gifs of
        */
        func searchGifs(for searchText: String) {
            network.fetchGifs(searchTerm: searchText) { gifArray in
                if gifArray != nil {
                    self.gifs = gifArray!.gifs
                    self.tableView.reloadData()
    
                }
                
            }
        }

**Comment by ibirnam** [comment]
@ellojess - thanks for flagging this for us, and for a working solution! This has been fixed in b24903c6b772e39cf336a386071bc15f20b25161 and you should see it live in the tutorial now!
