### ISSUE TITLE
Creating the Gif Object

### ISSUE THREAD

**Issue by KitsuneNoctus** [MakeSchool-Tutorials/Giphy-Search-iOS#2]
In Ch6 Creating the Gif Object - part: Decoding NSData into our new gif object, theres a slight error with
```
/**
    Fetches gifs based on the search term and populates tableview
    - Parameter searchTerm: The string to search gifs of
    */
    func fetchGifs(for searchText: String) {
        network.fetchGiphs(searchTerm: searchText) { results in
            if results != nil {
                print(results!.giphs.count)
                self.giphs = results!.giphs
                self.tableView.reloadData()
            }
        }
    }
```
In that gifs is not spelled the same way it it in the GifArray struct in the Gif.swift file here
Also, for the line `self.giphs = results!.giphs` there is no `self.giphs` as far as I can see
Added var gifs = [Gif]() at the top of view controller. IDK if that should be in the step. (edited)

**Comment by ibirnam** [comment]
@KitsuneNoctus - thanks for flagging this for us! This has been fixed in b24903c6b772e39cf336a386071bc15f20b25161 and you should see it live in the tutorial now!
